### ISSUE TITLE
Supported data stores

### ISSUE THREAD

**Issue by brandoncc** [reidmorrison/rocketjob#23]
Hello, thank you for this wonderful project.

I compared all of the Ruby job processors I could find, and was ready to try Rocket Job. Unfortunately, I think only supports mongoid? Are there plans to support other data stores? I usually use Sidekiq, but I am working on an application which needs guarantees not offered by Redis.

I really wish I could use Rocket Job with Postgres, and hope that becomes an option in the future!

**Comment by reidmorrison** [comment]
Unfortunately Rocket Job would not scale and perform on Postgres. It was attempted but since it is a relational database it failed to perform under heavy load with hundreds of workers. MongoDB easily scales to thousands of workers with a very small database instance, with automated failover and high availability that relational databases can only dream of. We believe in the right tool for the right job and use Postgres for the main database, but Postgres unfortunately did not work in a high volume batch processing environment.
Moving from Redis to MongoDB is relatively straight forward.

**Comment by reidmorrison** [comment]
Delayed Job is a great gem that already supports using Postgres as your data store. Highly recommend using it if it meets your scaling and batch requirements.

**Comment by brandoncc** [comment]
Thank you for this information @reidmorrison.
